blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name="post_list"),
    path('givelist/',  views.GiveListView.as_view(), name='give_list'),
    path('wantlist/', views.WantListView.as_view(), name='want_list'),
    path('givenew/', views.GiveCreateView.as_view(), name='give_new'),
    path('wantnew/', views.WantCreateView.as_view(), name='want_new'),
    path('profilelist/', views.ProfileListView.as_view(), name='profile_list'),
    path('profilenew/', views.ProfileCreateView.as_view(), name='profile_new'),
    path('give<int:pk>/',views.GiveDetailView.as_view(), name='give_detail'),
    path('want<int:pk>/', views.WantDetailView.as_view(), name='want_detail'),
    path('profile<int:pk>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('give/<int:pk>/comment/', views.add_comment_to_give, name='add_comment_to_give'),
    path('give/comment/<int:pk>/remove/', views.give_comment_remove, name='give_comment_remove'),
    path('want/<int:pk>/comment/', views.add_comment_to_want, name='add_comment_to_want'),
    path('profile/<int:pk>/comment/', views.add_comment_to_profile, name='add_comment_to_profile'),
    path('want/comment/<int:pk>/remove/', views.want_comment_remove, name='want_comment_remove'),
    path('comment/<int:pk>/remove/', views.give_comment_remove, name='give_comment_remove'),
    path('profile/comment/<int:pk>/remove/', views.profile_comment_remove, name='profile_comment_remove'),
    path('give-delete/<int:pk>/', views.GiveDeleteView.as_view(), name="give_delete"),
    path('give-update/<int:pk>/', views.GiveUpdateView.as_view(), name="give_update"),
    path('want-delete/<int:pk>/', views.WantDeleteView.as_view(), name="want_delete"),
    path('want-update/<int:pk>/', views.WantUpdateView.as_view(), name="want_update"),
    path('profile-delete/<int:pk>/', views.ProfileDeleteView.as_view(), name="profile_delete"),
    path('profile-update/<int:pk>/', views.ProfileUpdateView.as_view(), name="profile_update"),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser

class Profile(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField('社員名（※必須）',max_length=30)
    introduction = models.TextField('ひとこと（※任意）',max_length=200,null=True)
    photo = models.ImageField('プロフィール画像（※任意）',blank=True,null=True)
    register_date = models.DateTimeField('登録日時',auto_now_add=True, blank=True, null=True)
    final_update_time = models.DateTimeField('更新日時',auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name

class Profile_comment(models.Model):
    profile = models.ForeignKey('blog.Profile', on_delete=models.CASCADE, related_name='profile_comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField('コメント',null=True)
    created_date = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


class Give(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    give_name = models.CharField('タイトル（※必須）',max_length=50)
    give_information = models.TextField('詳細情報（※必須）',max_length=200,null=True)
    give_reason = models.TextField('あげたい理由（※任意）',max_length=200,null=True)
    delivery_infomation = models.CharField('引き渡し方法（※必須）',max_length=30,null=True)
    register_date = models.DateTimeField('登録日時',auto_now_add=True, blank=True, null=True)
    final_update_time = models.DateTimeField('更新日時',auto_now=True, blank=True, null=True)  
    photo = models.ImageField(verbose_name='イメージ写真（※任意）', blank=True, null=True)
    
    def __str__(self):
        return self.give_name

class Give_comment(models.Model):
    give = models.ForeignKey('blog.Give', on_delete=models.CASCADE, related_name='give_comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField('コメント',null=True)
    created_date = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

class Want(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    emergency = (
        ('1', '高'),
        ('2', '中'),
        ('3', '低'),
    )
    emergency_attribute = models.CharField('緊急度（※選択）',max_length=30,choices=emergency)
    want_name = models.CharField('タイトル（※必須）',max_length=50)
    want_information = models.TextField('詳細情報（※必須）',max_length=200,null=True)
    want_reason = models.TextField('ほしい理由（※任意）',max_length=200,null=True)
    register_date = models.DateTimeField('登録日時',auto_now_add=True, blank=True, null=True)
    final_update_time = models.DateTimeField('更新日時',auto_now=True, blank=True, null=True) 
    photo = models.ImageField(verbose_name='イメージ写真（※任意）', blank=True, null=True)

    def __str__(self):
        return self.want_name

class Want_comment(models.Model):
    want = models.ForeignKey('blog.Want', on_delete=models.CASCADE, related_name='want_comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField('コメント',null=True)
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/templates/sharesite/add_comment_to_want.html
{% extends 'sharesite/base.html' %}

{% block content %}
    <h1 class="text-center">コメントする</h1>
    <form method="POST" class="want-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-default waves-effect sub-button comment-button" style="font-size: 24px;">投稿</button>
    </form>
{% endblock %}

blog/templates/sharesite/base.html
{% load static %}
<html>
    <head>
        <title>SHARE SITE</title>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Your custom styles (optional) -->
        <link rel="stylesheet" href="{% static 'css/sharesite.css' %}">
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
<!---->
<nav class="navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="/"><strong class="header-title">SKY SHARE </strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
　　　　　
        <li class="nav-item">
          <a class="nav-link" href="{% url 'want_list' %}">ほしいリスト</a>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'give_list' %}">あげるリスト</a>         
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile_list' %}">プロフィールリスト<span class="sr-only">(current)</span></a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'want_new' %}">ほしい！</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'give_new' %}">あげる！</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile_new' %}">プロフィール新規作成</a>
        </li>
        {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
              </li>
            {% else %}
              <li class="nav-item {% block active_signup %}{% endblock %}">
                  <a class="nav-link" href="{% url 'account_signup' %}">ユーザー登録</a>
              </li>
              <li class="nav-item {% block active_login %}{% endblock %}">
                  <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
              </li>
            {% endif %}
      </ul>
    </div>
  </nav>

<!---->
    </header>
    <div>
      {% if messages %}
        <div class="container">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
      {% endif %}   
    {% block content %}
    {% endblock %}
    </div>


               <!-- Footer -->
<footer class="footer">

    <!-- Copyright -->
    <div class="footer-copyright text-center footer-text">SKY SHARE made by TeamB</div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
        <!-- JQuery -->
<script type="text/javascript" src="js/jquery-3.1.1.min.js"></script>

<!-- Bootstrap tooltips -->
<script type="text/javascript" src="js/tether.min.js"></script>

<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="js/bootstrap.min.js"></script>

<!-- MDB core JavaScript -->
<script type="text/javascript" src="js/mdb.min.js"></script>
    </body>
</html>

blog/templates/sharesite/give_detail.html
{% extends 'sharesite/base.html' %}
{% load static %}


{% block content %}
<div class="text-center">
    <br>
    <h2 style="font-weight:bold;">あげる詳細</h2>
    <br>
</div>
<div class="container">
    <div class="my-div-style w-100">
        
        <hr>
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.give_name|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>投稿者</strong>
            </div>
            <div class="col-9">
                {{ object.author }}
            </div>
        </div>

        <hr>
        <div class="row">
            <div class="col-3">
                <strong>詳細情報</strong>
            </div>
            <div class="col-9">
                {{ object.give_information|linebreaksbr }}
            </div>
        </div>

        <hr>
        
        <div class="row">
            <div class="col-3">
                <strong>あげる理由</strong>
            </div>
            <div class="col-9">
                {{ object.give_reason|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>引き渡し方法</strong>
            </div>
            <div class="col-9">
                {{ object.delivery_infomation|linebreaksbr }}
            </div>
        </div>
        
        <hr>

        <div class="row">
            <div class="col-3">
                <strong>画像</strong>
            </div>
            <div class="col-3">
                {% if object.photo %}
                    <img src="{{ object.photo.url }}" width="200" height="200"/>
                {% endif %}
            </div>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.register_date }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.final_update_time }}
            </div>
        </div>


    </div>
</div>
<hr>
<div class="comment-area">
<a class="btn btn-outline-warning waves-effect sub-button" style="font-size: 20px;padding: 2px;" href="{% url 'add_comment_to_give' pk=give.pk %}">コメントする</a>
<a class="btn btn-outline-default waves-effect sub-button" style="font-size: 24px;" href="{% url 'give_update' object.pk %}">編集</a>
<a class="btn btn-outline-info waves-effect sub-button" style="font-size: 24px;" href="{% url 'give_delete' object.pk %}">削除</a>
{% for comment in give.give_comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-outline-danger waves-effect sub-button" style="font-size: 20px;padding: 20px;" href="{% url 'give_comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>コメントはまだありません</p>
{% endfor %}

</div>
</div>
{% endblock %}

blog/templates/sharesite/give_edit.html
{% extends 'sharesite/base.html' %}

{% block content %}
<form method="POST" class="give_form">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">あげる</button>
</form>

{% endblock %}

blog/templates/sharesite/give_new.html
{% extends 'sharesite/base.html' %}

{% block content %}
<div class="text-center">
    <h2 class="body-title" style="font-weight:bold;">あげるを投稿する</h2>
</div>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-outline-default waves-effect sub-button" style="font-size: 20px;" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/sharesite/give_remove.html
{% extends 'sharesite/base.html' %}

{% block content %}

    <h2>本当に削除してよろしいですか？</h2>

    
{% endblock %}

blog/templates/sharesite/post_list.html
{% extends 'sharesite/base.html' %}

{% block content %}
<div class="post_list">
<div class="button_erea">
<button class="btn  btn-outline-success waves-effect button_per top-button-left"><a class="" href="{% url 'want_list' %}">ほしいです！</a></button>
<button class="btn  btn-outline-info waves-effect button_per top-button-right"><a class="" href="{% url 'give_list' %}">あげます！</a></button>
</div>
<div class="top-emr-mes text-center">
  <h2>すぐに欲しい人が待っています！</h2>
  <br>
  <h2 class="fuwafuwa">↓ ↓ ↓</h2>

</div>
</div>

<div class="row">
    {% for want in want_list %}
    {% if want.emergency_attribute == "1" %}
    <!-- Grid column -->
    <div class="col-lg-4 col-md-12 mb-4">
      <div class="view overlay rounded z-depth-1">
        {% if want.photo %}
        <img src="{{ want.photo.url }}" alt="No Photo" width="469.73" height="300">
        {% else %}
        <img src="#" alt="No photo" width="469.73" height="300">
        {% endif %}
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <div class="px-3 pt-3 mx-1 mt-1 pb-0 red-bg emr-bg">
        <h4 class="font-weight-bold mt-1 mb-3"><a href="{% url 'want_detail' pk=want.pk %}" class="body-title">{{ want.want_name }}</a></h4>
        <p class="text-muted body-text" >ほしい理由：<br>{{ want.want_reason|truncatechars:50 }}<a class="read-more" href="{% url 'want_detail' pk=want.pk %}">  >>続きを読む</a></p>
        <p class="body-text text-muted">投稿者：{{ want.author }}</p>
        <p class="body-text text-muted">緊急度：{{ want.get_emergency_attribute_display }}</p>
        <div class="view-detail">
        <a href="{% url 'want_detail' pk=want.pk %}" class="btn btn-outline-default waves-effect"><i class="fas fa-clone left"></i>詳細を見る</a>
      </div>
      <div class="comment-detail">
        <a href="{% url 'want_detail' pk=want.pk %}"class="body-text">コメント: {{ want.want_comments.count }}件</a>
      </div>
      </div>
    </div>
    <!-- Grid column -->
    {% elif want.emergency_attribute == "2" %}
    <!-- Grid column -->
    <div class="col-lg-4 col-md-12 mb-4">
      <div class="view overlay rounded z-depth-1">
        {% if want.photo %}
        <img src="{{ want.photo.url }}" alt="Sample project image" width="469.73" height="300">
        {% else %}
        <img src="#" alt="No photo" width="469.73" height="300">
        {% endif %}
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <div class="px-3 pt-3 mx-1 mt-1 pb-0 blue-bg emr-bg">
        <h4 class="font-weight-bold mt-1 mb-3"><a href="{% url 'want_detail' pk=want.pk %}" class="body-title">{{ want.want_name }}</a></h4>
        <p class="text-muted body-text" >欲しい理由：<br>{{ want.want_reason|truncatechars:50 }}<a class="read-more" href="{% url 'want_detail' pk=want.pk %}">  >>続きを読む</a></p>
        <p class="text-muted">投稿者：{{ want.author }}</p>
        <p class="text-muted">緊急度：{{ want.get_emergency_attribute_display }}</p>
        <a href="{% url 'want_detail' pk=want.pk %}" class="btn btn-outline-default waves-effect"><i class="fas fa-clone left"></i>詳細を見る</a>
        <a href="{% url 'want_detail' pk=want.pk %}"class="body-text">コメント: {{ want.want_comments.count }}件</a>
      </div>
    </div>
    <!-- Grid column -->
    {% else %}
    <!-- Grid column -->
    <div class="col-lg-4 col-md-12 mb-4">
      <div class="view overlay rounded z-depth-1">
        {% if want.photo %}
        <img src="{{ want.photo.url }}" alt="Sample project image" width="469.73" height="300">
        {% else %}
        <img src="#" alt="No photo" width="469.73" height="300">
        {% endif %}
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <div class="px-3 pt-3 mx-1 mt-1 pb-0 green-bg emr-bg">
        <h4 class="font-weight-bold mt-1 mb-3"><a href="{% url 'want_detail' pk=want.pk %}" class="body-title">{{ want.want_name }}</a></h4>
        <p class="text-muted body-text" >欲しい理由：<br>{{ want.want_reason|truncatechars:50 }}<a class="read-more" href="{% url 'want_detail' pk=want.pk %}">  >>続きを読む</a></p>
        <p class="text-muted">投稿者：{{ want.author }}</p>
        <p class="text-muted">緊急度：{{ want.get_emergency_attribute_display }}</p>
        <a href="{% url 'want_detail' pk=want.pk %}" class="btn btn-outline-default waves-effect"><i class="fas fa-clone left"></i>詳細を見る</a>
        <a href="{% url 'want_detail' pk=want.pk %}"class="body-text">コメント: {{ want.want_comments.count }}件</a>
      </div>
    </div>
    <!-- Grid column -->
    {% endif %}
    {% endfor %}
  </div>
  {% if is_paginated %}
  <div class="pagination-container">
  <ul class="pagination">
  
      {% if page_obj.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                  <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
      {% endif %}

  
      {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
              <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
          {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}

  
      {% if page_obj.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                  <span aria-hidden="true">&raquo;</span>
              </a>
          </li>
      {% endif %}
  </ul>
</div>
　　{% endif %}
{% endblock %}

blog/templates/sharesite/profile_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}投稿編集 |Sharesite{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-outline-default waves-effect sub-button" style="font-size: 24px;" type="submit">更新</button>
                <a class="btn btn-outline-info waves-effect sub-button" style="font-size: 24px;" href="{% url 'profile_detail' object.pk %}">戻る</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/sharesite/want_list.html
{% extends 'sharesite/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <!-- Section: Block Content -->
    <section class="dark-grey-text text-center">
      <h3 class="font-weight-bold mb-4 pb-2 list-title">ほしいリスト</h3>
      <p class="text-muted w-responsive mx-auto mb-5">みんなの今ほしいものが載っています。<br>あげられるものがあればコメントしてみましょう！</p>
      <!-- Grid row -->
      <div class="row">
        {% for want in want_list %}
        {% if want.emergency_attribute == "1" %}
        <!-- Grid column -->
        <div class="col-lg-4 col-md-12 mb-4">
          <div class="view overlay rounded z-depth-1">
            {% if want.photo %}
            <a href="{% url 'want_detail' pk=want.pk %}"><img src="{{ want.photo.url }}"  alt="No photo" width="469.73" height="300"></a>
            {% else %}
            <a href="{% url 'want_detail' pk=want.pk %}"><img src="#" alt="No photo" width="469.73" height="300"></a>
            {% endif %}
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <div class="px-3 pt-3 mx-1 mt-1 pb-0 red-bg emr-bg">
            <h4 class="font-weight-bold mt-1 mb-3"><a class="body-title" href="{% url 'want_detail' pk=want.pk %}">{{ want.want_name }}</a></h4>
            <p class="text-muted body-text text-left">ほしい理由：<br>{{ want.want_reason|truncatechars:50 }}<a class="read-more" href="{% url 'want_detail' pk=want.pk %}">  >>続きを読む</a></p>
            <p class="text-muted body-text text-left">投稿者：{{ want.author }}</p>
            <p class="text-muted body-text text-left">緊急度：{{ want.get_emergency_attribute_display }}</p>
            <div class="view-detail">
            <a href="{% url 'want_detail' pk=want.pk %}" class="btn btn-outline-default waves-effect"><i class="fas fa-clone left"></i> View Detail</a>
          </div>
          <div class="comment-detail">
            <a href="{% url 'want_detail' pk=want.pk %}">コメント: {{ want.want_comments.count }}件</a>
          </div>
          </div>
        </div>
        <!-- Grid column -->
        {% elif want.emergency_attribute == "2" %}
        <!-- Grid column -->
        <div class="col-lg-4 col-md-12 mb-4 ">
          <div class="view overlay rounded z-depth-1">
            {% if want.photo %}
            <a href="{% url 'want_detail' pk=want.pk %}"><img src="{{ want.photo.url }}"  alt="No photo" width="469.73" height="300"></a>
            {% else %}
            <a href="{% url 'want_detail' pk=want.pk %}"><img  src="#" alt="No photo" width="469.73" height="300"></a>
            {% endif %}
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <div class="px-3 pt-3 mx-1 mt-1 pb-0 blue-bg emr-bg">
            <h4 class="font-weight-bold mt-1 mb-3"><a class="body-title" href="{% url 'want_detail' pk=want.pk %}">{{ want.want_name }}</a></h4>
            <p class="text-muted body-text text-left">ほしい理由：<br>{{ want.want_reason|truncatechars:50 }}<a class="read-more" href="{% url 'want_detail' pk=want.pk %}">  >>続きを読む</a></p>
            <p class="text-muted body-text text-left">投稿者：{{ want.author }}</p>
            <p class="text-muted body-text text-left">緊急度：{{ want.get_emergency_attribute_display }}</p>
            <div class="view-detail">
            <a href="{% url 'want_detail' pk=want.pk %}" class="btn btn-outline-default waves-effect"><i class="fas fa-clone left"></i> View Detail</a>
          </div>
          <div class="comment-detail">
            <a href="{% url 'want_detail' pk=want.pk %}">コメント: {{ want.want_comments.count }}件</a>
          </div>
          </div>
        </div>
        <!-- Grid column -->
        {% else %}
        <!-- Grid column -->
        <div class="col-lg-4 col-md-12 mb-4">
          <div class="view overlay rounded z-depth-1">
            {% if want.photo %}
            <a href="{% url 'want_detail' pk=want.pk %}"><img src="{{ want.photo.url }}"  alt="No photo" width="469.73" height="300"></a>
            {% else %}
            <a href="{% url 'want_detail' pk=want.pk %}"><img src="#" alt="No photo" width="469.73" height="300"></a>
            {% endif %}
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <div class="px-3 pt-3 mx-1 mt-1 pb-0 green-bg emr-bg">
            <h4 class="font-weight-bold mt-1 mb-3"><a class="body-title" href="{% url 'want_detail' pk=want.pk %}">{{ want.want_name }}</a></h4>
            <p class="text-muted body-text text-left">ほしい理由：<br>{{ want.want_reason|truncatechars:50 }}<a class="read-more" href="{% url 'want_detail' pk=want.pk %}">  >>続きを読む</a></p>
            <p class="text-muted body-text text-left">投稿者：{{ want.author }}</p>
            <p class="text-muted body-text text-left">緊急度：{{ want.get_emergency_attribute_display }}</p>
            <div class="view-detail">
            <a href="{% url 'want_detail' pk=want.pk %}" class="btn btn-outline-default waves-effect"><i class="fas fa-clone left"></i> View Detail</a>
          </div>
          <div class="comment-detail">
            <a class="body-text" href="{% url 'want_detail' pk=want.pk %}">コメント: {{ want.want_comments.count }}件</a>
          </div>
          </div>
        </div>
        <!-- Grid column -->
        {% endif %}
        {% endfor %}
      </div>
      <!-- Grid row -->
    </section>
    <!-- Section: Block Content -->
  </div>
    {% if is_paginated %}
    <div class="pagination-container">
    <ul class="pagination">
    
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

    
        {% for page_num in page_obj.paginator.page_range %}
            {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}

    
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
  </div>
　　{% endif %}
{% endblock %}